### ISSUE TITLE
Capstone: PWP - Murder Mystery

### ISSUE THREAD

**Issue by cviddy17** [Jeanelh/pwp-capstones#1]
### Criteria 1: Valid Python Code
* _Score Level:_ 4/4 Exceeds Expectations
* _Comment(s):_ Notebook functions as intended and code produces results accordingly without errors.
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 4/4 Exceeds Expectations
* _Comment(s):_ Code was well implemented, and took all pieces of the puzzle into consideration.
 
### Criteria 3: Software Architecture
* _Score Level:_ 4/4 Exceeds Expectations
* _Comment(s):_ Functions and classes were built out correctly. Great job!
 
### Criteria 4: Uses Python Language Features
* _Score Level:_ 4/4 Meets Expectations
* _Comment(s):_ Using replace is a very creative way of removing punctuation without importing any additional libraries, but consider the strip function as well. Overall, great job!

### Criteria 5: Produces Accurate Output
* _Score Level:_ 4/4 Exceeds Expectations
* _Comment(s):_ Your analysis took everything into consideration and was correct based off of your algorithms! Great job!
 
### Overall Score: 20/20
Excellent job! Your code was easy to follow, well commented and produced accurate results!

**Comment by Jeanelh** [comment]
Thanks for the positive feedback. I found using Jupyter very challenging. As for using the strip function - I TRIED! I could not get it to work at all, so I will revisit it and see if I can use it properly. It was my understanding that strip( ) removes white space from the end of a string. 

BTW - I found the upload process for GitHub confusing as well. Since I have never used either GitHub or Jupyter outside of this course, it was an added challenge to the course.

Thanks again for your feedback and quick response. Sincerely,
Jeanel
